# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(SourceBranchName)$(Rev:.r)

trigger:
- master
- release/*

pr:
- master
- release/*

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  dotnetcore.version: '2.1.403'

steps:
#- task: DotNetCoreInstaller@0
#  displayName: 'Use .NET Core sdk 2.1.500'
#  inputs:
#    version: 2.1.500

- powershell: |
   If ($env:BUILD_BUILDNUMBER -match "^\d+\.\d+\.\d+\.\d+$") {
       $version = $env:BUILD_BUILDNUMBER
   } Else {
       $version = $env:BUILD_BUILDNUMBER -replace "^.+\.(\d+)$", '1.0.0.$1'
   }
   Write-Host "##vso[task.setvariable variable=Version]$version"
   Write-Host "Computed version: $version"
  failOnStderr: true
  displayName: 'Compute version'
  
- script: dotnet build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -p:Version=$(version)
  displayName: 'dotnet build $(buildConfiguration)'
 
#- task: VisualStudioTestPlatformInstaller@1
#  displayName: 'Visual Studio Test Platform Installer'
  
#- task: VSTest@2
#  displayName: 'Run tests'
#  inputs:
#    testAssemblyVer2: |
#     test\**\*Tests.dll
#     !**\*TestAdapter.dll
#     !**\obj\**
#    runInParallel: true
#- task: DotNetCoreCLI@2
#  displayName: 'dotnet test'
#  inputs:
#    command: test
#    projects: 'test/**/*.csproj'
#    arguments: '--configuration $(BuildConfiguration)'
    
#- task: DotNetCoreCLI@2
#  displayName: 'dotnet pack'
#  inputs:
#    command: pack
#    packagesToPack: 'src/**/*.csproj'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)\src'
  inputs:
    SourceFolder: src
    TargetFolder: '$(Build.ArtifactStagingDirectory)\src'
  
- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
